batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403101244
train_epochs: 20
train_workers: 20
vocab: se43NyHfQTlSAD?.0cJ#/6(:*MnFi+vrqbRx,)oCaOgdp57KUz'&PVEW;-GI89ZmtukX1LY !w"hB2j
width: 1408
