batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403101656
train_epochs: 5
train_workers: 20
vocab: 'P:E3M2loLF,&.?wTKO"5Wre4ak9QXxuBUIN0bGqim1p*nAD7SHf)8C;czdgJy!V-tv+sj #6''RZ/Yh('
width: 1408
