batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403161511
train_epochs: 15
train_workers: 20
vocab: Yjq9,82K7A!;xG'6Z.whgd45yIzMoeQs-kR0JC1b/?aUDiPH"*XE)LT O:3#NpFBfVutcS+r&vWmnl(
width: 1408
