batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403161319
train_epochs: 15
train_workers: 20
vocab: 6OvwG3haq)f.'4nloH;kP:z&N1A82F5DV7#Ty,Q0JIRUsZd"WE(/KYr-bcLiC*Bj+ugp!xtMeX9?
  Sm
width: 1408
