batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403091432
train_epochs: 20
train_workers: 20
vocab: 4+tQ82*Kz-rvS:?#mxpICDdTW9c3Rj!HPy15VF,;w"q'Nb/XEo06)YkiO&lu Jg7LMshfAeBZnaGU(.
width: 1408
