batch_size: 5
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403171133
train_epochs: 15
train_workers: 20
vocab: 4#51/eqV;3AmzWZ6Cr:-XnRK0hug&w)o,jS'2tyIxvcM.UF!fO T"PNEkYaJliHsQ7b+dpGD(?B9*8L
width: 1408
